accounts/urls.py
from django.conf.urls import url
from accounts.views import UserLoginView, UserRegisterView, LogoutView

urlpatterns = [
    url(r'^login/', UserLoginView.as_view(), name='login'),
    url(r'^register/', UserRegisterView.as_view(), name='register'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
]

portanizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',
        RedirectView.as_view(pattern_name='posts:index')),
    url(r'^authorization/',
        include(('authorization.urls', 'authorization'), namespace='authorization')),
    url(r'^posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

posts/urls.py
from django.conf.urls import url
from .views import (
    PostListView,
    CreatePostFormView,
    UpdatePostFormView,
    TagManagerView,
    DeletePostView,
)

from .viewsets import PostListViewSet

urlpatterns = [
    url(r'^$',
        PostListView.as_view(), name='index'),
    url(r'^create/',
        CreatePostFormView.as_view(), name='create'),
    url(r'^update/(?P<pk>[0-9]+)/',
        UpdatePostFormView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/',
        DeletePostView.as_view(), name='delete'),
    url(r'^tagmanager/$',
        TagManagerView.as_view(), name='tagmanager'),
    url(r'^api/$',
        PostListViewSet.as_view(), name='post_api'),
]

posts/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    body = models.TextField()
    tag = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:update', kwargs={'pk': str(self.id)})


class Tag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

posts/forms.py
from django import forms
from .models import Tag, Post


class TagModelForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']
        labels = {
            "name": "New tag"
        }

    def __init__(self, user, *args, **kwargs):
        super(TagModelForm, self).__init__(*args, **kwargs)

        self.user = user

    def clean_name(self):
        if self.has_changed():
            data = self.cleaned_data['name']
            try:
                tag = Tag.objects.get(name=data, user=self.user)
            except Tag.DoesNotExist:
                tag = None
            if tag:
                raise forms.ValidationError(
                    "\"%s\" already exists for user %s" % (tag.name, self.user)
                )
            return data


class TagMultiplyForm(forms.Form):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TagMultiplyForm, self).__init__(*args, **kwargs)

        self.fields['tag'] = forms.ModelMultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            queryset=Tag.objects.filter(user=user).order_by('name'),
            to_field_name="name"
        )


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'tag']

    def __init__(self, request, *args, **kwargs):
        super(PostModelForm, self).__init__(*args, **kwargs)
        queryset = Tag.objects.filter(user=request.user)
        self.fields['tag'].queryset = queryset


def custom_tag_base_modelformset(user):
    class TagBaseModelFormSet(forms.BaseModelFormSet):

        def __init__(self, *args, **kwargs):
            self.user = user
            super(TagBaseModelFormSet, self).__init__(*args, **kwargs)

        # https://docs.djangoproject.com/en/1.11/topics/forms/formsets/#custom-formset-validation
        def clean(self):
            if any(self.errors):
                print(self.errors)
                return

            for form in self.forms:
                if form.has_changed():
                    data = form.cleaned_data['name']
                    try:
                        tag = Tag.objects.get(name=data, user=self.user)
                    except Tag.DoesNotExist:
                        tag = None
                    if tag:
                        form.add_error(
                            'name', "\"%s\" already exists for user %s" % (
                                tag.name, self.user))

    return TagBaseModelFormSet

posts/views.py
import math

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from django.db.models import Q
from django.db.models import Count
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from .models import Post, Tag
from .forms import TagModelForm, PostModelForm, custom_tag_base_modelformset


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'index.html'

    def get_queryset(self):
        queryset = Post.objects.filter(user=self.request.user)

        tags = self.request.GET.getlist('tag')
        condition = self.request.GET.get('condition')
        unassigned = self.request.GET.get('show_unassigned')

        # do not use unassigned when condition and tags are present
        if condition and tags:
            unassigned = None

        if unassigned and tags:
            return queryset.filter(
                Q(tag__isnull=True) | Q(tag__name__in=tags)).distinct()
        elif unassigned:
            return queryset.filter(tag__isnull=True)
        elif tags:
            if condition:
                # return posts which include all tags
                return queryset.filter(tag__name__in=tags).annotate(
                    matched_tags=Count('tag')).filter(matched_tags=len(tags))

            # return posts matched any of tags
            return queryset.filter(tag__name__in=tags).distinct()
        return queryset


class CreatePostFormView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    form_class = PostModelForm
    template_name = 'post.html'
    success_url = '/posts/'
    success_message = "%(title)s was created successfully"

    def get_context_data(self, **kwargs):
        context = super(CreatePostFormView, self).get_context_data(**kwargs)

        context['formNewTag'] = TagModelForm(self.request.user)

        # if formNewTag in kwargs - replace existed
        context.update(kwargs)
        return context

    def post(self, request, *args, **kwargs):
        # to overcome the issue has no attribute 'object'
        self.object = None

        formTag = TagModelForm(request.user, request.POST)

        # Separate processes for two forms based on name html attribute
        if 'tag_submit' in request.POST:
            if formTag.is_valid():
                new_tag = formTag.save(commit=False)
                new_tag.user = self.request.user
                new_tag.save()

                return render(
                    request,
                    self.template_name,
                    self.get_context_data())
            else:
                return render(
                    request,
                    self.template_name,
                    self.get_context_data(formNewTag=formTag))

        # Return the standard post method if the New tag is not specified
        return super(
            CreatePostFormView, self).post(self, request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreatePostFormView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        self.object = instance
        return super(CreatePostFormView, self).form_valid(form)


class UpdatePostFormView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostModelForm
    template_name = 'post.html'
    success_url = '/posts/'
    success_message = "%(title)s was updated successfully"

    def get_context_data(self, **kwargs):
        context = super(UpdatePostFormView, self).get_context_data(**kwargs)

        # to get the pk's
        context.update(self.kwargs)

        context['formNewTag'] = TagModelForm(self.request.user)

        # if formNewTag in kwargs - replace existed
        context.update(kwargs)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        formTag = TagModelForm(request.user, request.POST)

        # Separate processes for two forms based on name html attribute
        if 'tag_submit' in request.POST:
            if formTag.is_valid():
                new_tag = formTag.save(commit=False)
                new_tag.user = self.request.user
                new_tag.save()

                return render(
                    request,
                    self.template_name,
                    self.get_context_data())
            else:
                return render(
                    request,
                    self.template_name,
                    self.get_context_data(formNewTag=formTag))

        # Return the standard post method if the New tag is not specified
        return super(
            UpdatePostFormView, self).post(self, request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(UpdatePostFormView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        self.object = instance
        return super(UpdatePostFormView, self).form_valid(form)


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'confirm_delete.html'
    success_url = '/'


class TagManagerView(LoginRequiredMixin, TemplateView):

    template_name = 'tag_manager.html'

    def get_context_data(self, **kwargs):
        context = super(TagManagerView, self).get_context_data(**kwargs)

        # gets formset from get and post methods
        context.update(kwargs)

        # delimeter for columns
        # -1 - extra form, then round to up value
        context['column_count'] = math.ceil(
            (kwargs['formset'].total_form_count() - 1) / 3)
        return context

    def get(self, request, *args, **kwargs):
        queryset = Tag.objects.filter(user=self.request.user).order_by('-name')

        formset = custom_tag_base_modelformset(request.user)

        # https://djangosnippets.org/snippets/2552/
        # https://stackoverflow.com/questions/622982/django-passing-custom-form-parameters-to-formset/25766319#25766319
        TagFormSet = modelformset_factory(
            Tag,
            formset=formset,
            fields=('name',),
            can_delete=True)

        formset = TagFormSet(queryset=queryset)
        return self.render_to_response(self.get_context_data(
            formset=formset))

    def post(self, request, *args, **kwargs):
        # https://stackoverflow.com/questions/34214547/modifying-a-inline-formset-before-it-is-saved

        formset = custom_tag_base_modelformset(request.user)

        TagFormSet = modelformset_factory(
            Tag,
            formset=formset,
            fields=('name',),
            can_delete=True)

        formset = TagFormSet(request.POST)

        if formset.is_valid():
            instances = formset.save(commit=False)
            for instance in instances:
                instance.user = self.request.user
                # you’ll also need to call formset.save_m2m()
                # to ensure the many-to-many relationships are saved properly.
                instance.save()

            for instance in formset.deleted_objects:
                instance.delete()
            return redirect('posts:tagmanager')
        else:
            return self.render_to_response(self.get_context_data(
                formset=formset))

posts/templates/confirm_delete.html
{% extends "header.html" %}
{% block content %}
<div class="well well-sm">
  <form class="form-group" action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"? <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-trash" aria-hidden="true"></button></p>
  </form>
</div>
{% endblock content %}

posts/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portanizer</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/dropdowns-enhancement.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-toggle.min.css' %}" type = "text/css"/>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/dropdowns-enhancement.js' %}"></script>
    <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top porta-navbar"><!--navbar navbar-inverse-->
    <div class="container"><!--container-fluid-->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand" href="{% url 'posts:index' %}">Portanizer</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li>{% include "includes/panel.html" %}</li>
          {# <li><input type="checkbox" checked data-toggle="toggle" data-on="Any" data-off="Only" data-onstyle="success" data-offstyle="warning" data-size="small"></li> #}
          <li><a href="{% url 'posts:create' %}">Create Post</a></li>
          <li><a href="{% url 'posts:tagmanager' %}">Tag Manager</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href=""><span class="glyphicon glyphicon-user"></span> {{request.user.username}}</a></li>
          <li><a href="{% url 'authorization:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
</body>
</html>

posts/templates/index.html
{% extends "header.html" %}
{% block content %}
            {% include "includes/posts.html" %}
{% endblock content %}

posts/templates/post.html
{% extends "header.html" %}
{% block content %}
{% load widget_tweaks %}
<div class="row">
  <div class="col-xs-12">
    <div class="well well-sm">

      {% url 'updatepost' pk as url_updatepost %}
      {% if request.path == url_updatepost %}  
        <div class="form-group">
          <a href="{% url 'deletepost' pk %}" class="btn btn-default">
            <span class="glyphicon glyphicon-trash"></span>
          </a>
        </div>
      {% endif %}
      
      <form action ="" method="post" novalidate>{% csrf_token %}        
        <div class="row form-group">
          <div class="col-xs-8">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            {% render_field form.title class="form-control" placeholder="Enter post title" %}
            {{ form.title.errors }}
          </div>
        </div>
        <div class="row form-group">
          <div class="col-xs-12">
            <label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
            {% render_field form.body class="form-control" placeholder="Enter main body" %}
            {{ form.body.errors }}
          </div>
        </div>      
        <div class="row form-group">
          <div class="col-xs-4">
            <label for="{{ form.tag.id_for_label }}">{{ form.tag.label }}</label>
            {% render_field form.tag class="form-control" %}
            {{ form.tag.errors }}
          </div>
          <div class="col-xs-4">
            <label for="{{ formNewTag.name.id_for_label }}">{{ formNewTag.name.label }}</label>
            <div class = "input-group">
              {% render_field formNewTag.name class="form-control" placeholder="Enter new tag name" %}
              <div class="input-group-btn">
                <button name="tag_submit" type="submit" class="btn btn-default">
                  <span class="glyphicon glyphicon-save"></span>
                </button>
              </div>
            </div>
            {{ formNewTag.name.errors }}
          </div>
        </div><!--row form-group-->

        <div class="form-group">
          <button name="post_submit" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-ok"></span>
          </button>
        </div>
      </form> 
    </div><!--well-->
  </div><!--col-->
</div><!--row-->
{% endblock content %}s

posts/templates/tag_manager.html
{% extends "header.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
  <div class="col-xs-12">
    <div class="well well-sm">
   
      <form action ="" method="post" novalidate>{% csrf_token %}      
      {{ formset.management_form }}

        <div class="row bottom-buffer">
          {% for form in formset reversed %}
          {{form.id}}

          {% if forloop.first %}
          <div class="col-xs-4 col-add-mrg">
            <label for="id_name">New tag</label>
            {% render_field form.name class="form-control" placeholder="Enter new tag"%}
            {{form.name.errors}}
          </div>
        </div>
          
        <div class="row bottom-buffer">
          <div class="col-xs-4 col-add-mrg">

          {% else %}
              <div class = "input-group">
                {% render_field form.name class="form-control" %}
                <span class="input-group-addon">
                  {% render_field form.DELETE class="checkbox big-checkbox" %}
                </span>
              </div>
              {{form.name.errors}}

            {# count starts from 2 because of extra form #}
            {% if forloop.counter|add:-1|divisibleby:column_count and not forloop.last %}
          </div>
          <div class="col-xs-4 col-add-mrg">
            {% endif %}

          {% endif %} 
          {% endfor %}
          </div><!--col-->
        </div><!--row-->

        <div class="row col-add-mrg">
          <div class="col-xs-4 col-add-mrg">
            <button type="submit" class="btn btn-default">
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            </button>
          </div>
        </div>

      </form>
      
    </div><!--well-->
  </div><!--col-->
</div><!--row-->
{% endblock content %}